name: LPExcavator
main: pl.lifelesspixels.lpexcavator.LPExcavator
version: 0.1
api-version: 1.19
depend: [LPUtilities, LPChestGUI]
commands:
  excavator:
    description: Used to open GUI settings screen for the excavator
permissions:
  lpexcavator.command.excavator:
    default: true